### ISSUE TITLE
Not detecting bonus XP on heirloom items

### ISSUE THREAD

**Issue by DMCK96** [peterwooley/bonusxp#6] opened 2020-07-05 01:21 UTC
Detecting words of wisdom and enlisted fine, but not detecting any heirlooms at all. Tried re-equipping but made no difference.

**LUA Error:**

> x2  BonusXP\BonusXP-1.3.1.lua:718: attempt to index local 'item' (a nil value)
Stack: [string "@BonusXP\BonusXP-1.3.1.lua"]:718: in function 'onEventHandler'
[string "@BonusXP\BonusXP-1.3.1.lua"]:784: in function <BonusXP\BonusXP.lua:783>
Time: 2020/07/05 02:12:15 Index: 2/2
RealUI Version: 2.2.0
Locals:
self =  {
    getMapTopParentInfo = function @BonusXP\BonusXP.lua:195
    updateTooltipText = function @BonusXP\BonusXP.lua:552
    calculateEquipment = function @BonusXP\BonusXP.lua:489
    getDetails = function @BonusXP\BonusXP.lua:851
    getItemLinkInfo = function @BonusXP\BonusXP.lua:795
    refreshSpellData = function @BonusXP\BonusXP.lua:398
    setup = function @BonusXP\BonusXP.lua:769
    readFullItemData = function @BonusXP\BonusXP.lua:748
    isMemberVisible = function @BonusXP\BonusXP.lua:332
    updateBuffListText = function @BonusXP\BonusXP.lua:621
    getGroupInfo = function @BonusXP\BonusXP.lua:344
    registerEvents = function @BonusXP\BonusXP.lua:225
    getAuraXpBonus = function @BonusXP\BonusXP.lua:298
    refreshEquipDataSlot = function @BonusXP\BonusXP.lua:432
    isWowAnniversaryAura = function @BonusXP\BonusXP.lua:282
    getItemAuraXpBonus = function @BonusXP\BonusXP.lua:270
    onPlayerReady = function @BonusXP\BonusXP.lua:643
    getContinentId = function @BonusXP\BonusXP.lua:204
    updateButton = function @BonusXP\BonusXP.lua:791
    updateRAFText = function @BonusXP\BonusXP.lua:574
    updateUI = function @BonusXP\BonusXP.lua:241
    updateTooltipSize = function @BonusXP\BonusXP.lua:261
    updateBuffText = function @BonusXP\BonusXP.lua:559
    refreshEquipData = function @BonusXP\BonusXP.lua:477
    updateGearInfo = function @BonusXP\BonusXP.lua:540
    calculateBonus = function @BonusXP\BonusXP.lua:249
    initialize = function @BonusXP\BonusXP.lua:211
    onEventHandler = function @BonusXP\BonusXP.lua:656
    updateEquipmentListText = function @BonusXP\BonusXP.lua:632
    updateEquipmentText = function @BonusXP\BonusXP.lua:588
    getSpInfoBonus = function @BonusXP\BonusXP.lua:276
}
self = nil
event = "HEIRLOOMS_UPDATED"
arg1 = nil
arg2 = nil
arg3 = nil
arg4 = nil
arg5 = nil
cnt = 8
(for index) = 1
(for limit) = 8
(for step) = 1
i = 1
itemId = nil
item = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'item' (a nil value)"
isPlayerReadyFired = true
BonusXP =  {
    getMapTopParentInfo = function @BonusXP\BonusXP.lua:195
    updateTooltipText = function @BonusXP\BonusXP.lua:552
    calculateEquipment = function @BonusXP\BonusXP.lua:489
    getDetails = function @BonusXP\BonusXP.lua:851
    getItemLinkInfo = function @BonusXP\BonusXP.lua:795
    refreshSpellData = function @BonusXP\BonusXP.lua:398
    setup = function @BonusXP\BonusXP.lua:769
    readFullItemData = function @BonusXP\BonusXP.lua:748
    isMemberVisible = function @BonusXP\BonusXP.lua:332
    updateBuffListText = function @BonusXP\BonusXP.lua:621
    getGroupInfo = function @BonusXP\BonusXP.lua:344
    registerEvents = function @BonusXP\BonusXP.lua:225
    getAuraXpBonus = function @BonusXP\BonusXP.lua:298
    refreshEquipDataSlot = function @BonusXP\BonusXP.lua:432
    isWowAnniversaryAura = function @BonusXP\BonusXP.lua:282
    getItemAuraXp

**Comment by peterwooley** [comment] 2020-07-05 03:50
Thanks for submitting this! It looks like the code is failing on the first heirloom (and may continue failing on the others if it didn’t error out). Would you be willing to share the names of the heirloom gear you’re using (or just your headpiece if it’s too much hassle)? I’m not sure it’s item dependent, but I’d like to see if I can reproduce it.

**Comment by DMCK96** [comment] 2020-07-06 20:46
> Thanks for submitting this! It looks like the code is failing on the first heirloom (and may continue failing on the others if it didn’t error out). Would you be willing to share the names of the heirloom gear you’re using (or just your headpiece if it’s too much hassle)? I’m not sure it’s item dependent, but I’d like to see if I can reproduce it.

Yeah of course! 

First I'm a Void Elf Mage. 

These are my equipped heirlooms:
- Tattered Dreadmist Mask
- Eternal Emberfury Talisman
- Tattered Dreadmist Mantle
- Ancient Bloodmoon Cloak
- Tattered Dreadmist Robe
- Tattered Dreadmist LEggings
- Swift Hand of Justice (x2)
- Grand Staff of Jordan

**Comment by peterwooley** [comment] 2020-07-08 02:52
I'm having trouble reproducing this issue. I've set up a Void Elf mage in matching gear at level 20. I also installed RealUI (alongside Bonus XP) but was unable to replicate the problem. I've got a few more questions if you're open to answering them.

1. What level is your Void Elf mage?
2. Are all of your heirloom items upgraded beyond your current level?
3. If you `/reload` your UI after seeing the error, do you continue to get the error?
4. If the error stops after a `/reload`, do the heirloom bonuses show up then?
5. Did you use earlier versions of the Bonus XP add-on?
	* A saved variable used to be stored that may be causing an issue. You can delete the saved variable by deleting the file found under `<World of Warcraft Directory>/_retail_/WTF/Account/<Account Name>/SavedVariables/BonusXP.lua`
6. Do you have any other characters (at any level) where this error occurs?

I'm sorry it's taking a while to track down, but thanks for helping.

**Comment by peterwooley** [comment] 2020-09-12 08:00
Closing. If you see this happen again, re-open and let me know the answers to the questions in the comment above.

**Closed as completed by peterwooley** 2020-09-12 08:00 UTC
Labels: bug
